# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Estimation <- function(Y, Z0, Sinit, Ainit, Binit, Cinit, optsList) {
    .Call(`_tensorGMam_Estimation`, Y, Z0, Sinit, Ainit, Binit, Cinit, optsList)
}

setuplambda <- function(Y, Z0, Sinit, Ainit, Binit, Cinit, nx, ng, nlam, setlam) {
    .Call(`_tensorGMam_setuplambda`, Y, Z0, Sinit, Ainit, Binit, Cinit, nx, ng, nlam, setlam)
}

EstPenColumn <- function(Y, Z0, Sinit, Ainit, Binit, Cinit, lambda, optsList, optsList_pen) {
    .Call(`_tensorGMam_EstPenColumn`, Y, Z0, Sinit, Ainit, Binit, Cinit, lambda, optsList, optsList_pen)
}

EstPenColumnCV <- function(Y, Z0, Ytest, Ztest0, Sinit, Ainit, Binit, Cinit, lambda, optsList, optsList_pen) {
    .Call(`_tensorGMam_EstPenColumnCV`, Y, Z0, Ytest, Ztest0, Sinit, Ainit, Binit, Cinit, lambda, optsList, optsList_pen)
}

EstimationT4 <- function(Y, Z, S, A, B, C, D, optsList) {
    .Call(`_tensorGMam_EstimationT4`, Y, Z, S, A, B, C, D, optsList)
}

setuplambdaT4 <- function(Y, Z, S, A, B, C, D, nlam, setlam) {
    .Call(`_tensorGMam_setuplambdaT4`, Y, Z, S, A, B, C, D, nlam, setlam)
}

EstPenColumnT4 <- function(Y, Z, S, A, B, C, D, lambda, optsList, optsList_pen) {
    .Call(`_tensorGMam_EstPenColumnT4`, Y, Z, S, A, B, C, D, lambda, optsList, optsList_pen)
}

EstPenColumnT4CV <- function(Y, Z, Ytest, Ztest, S, A, B, C, D, lambda, optsList, optsList_pen) {
    .Call(`_tensorGMam_EstPenColumnT4CV`, Y, Z, Ytest, Ztest, S, A, B, C, D, lambda, optsList, optsList_pen)
}

TransferModalUnfoldingsT <- function(S, d1, d2, dims) {
    .Call(`_tensorGMam_TransferModalUnfoldingsT`, S, d1, d2, dims)
}

EstimationD3 <- function(Y, Z) {
    .Call(`_tensorGMam_EstimationD3`, Y, Z)
}

